//
// Copyright 2018-2025 Secberus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: api/v1/push.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/secberus/go-push-api/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTableInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table *v1.Table `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *CreateTableInput) Reset() {
	*x = CreateTableInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableInput) ProtoMessage() {}

func (x *CreateTableInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableInput.ProtoReflect.Descriptor instead.
func (*CreateTableInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTableInput) GetTable() *v1.Table {
	if x != nil {
		return x.Table
	}
	return nil
}

type CreateTableOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *CreateTableOutput) Reset() {
	*x = CreateTableOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableOutput) ProtoMessage() {}

func (x *CreateTableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableOutput.ProtoReflect.Descriptor instead.
func (*CreateTableOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTableOutput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type DropTableInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *DropTableInput) Reset() {
	*x = DropTableInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableInput) ProtoMessage() {}

func (x *DropTableInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableInput.ProtoReflect.Descriptor instead.
func (*DropTableInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *DropTableInput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type DropTableOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *DropTableOutput) Reset() {
	*x = DropTableOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableOutput) ProtoMessage() {}

func (x *DropTableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableOutput.ProtoReflect.Descriptor instead.
func (*DropTableOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{3}
}

func (x *DropTableOutput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// AddColumnOperation adds a new column to the table.
type AddColumnOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column *v1.Column `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *AddColumnOperation) Reset() {
	*x = AddColumnOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddColumnOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddColumnOperation) ProtoMessage() {}

func (x *AddColumnOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddColumnOperation.ProtoReflect.Descriptor instead.
func (*AddColumnOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{4}
}

func (x *AddColumnOperation) GetColumn() *v1.Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// DropColumnOperation removes a column from the table.
type DropColumnOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnName string `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
}

func (x *DropColumnOperation) Reset() {
	*x = DropColumnOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropColumnOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropColumnOperation) ProtoMessage() {}

func (x *DropColumnOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropColumnOperation.ProtoReflect.Descriptor instead.
func (*DropColumnOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{5}
}

func (x *DropColumnOperation) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

// AlterColumnOperation redefines an existing column. The column identified by
// column_name is replaced with the definition in column. The column name inside
// column may differ from column_name to effect a rename alongside a type change.
type AlterColumnOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnName string     `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	Column     *v1.Column `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *AlterColumnOperation) Reset() {
	*x = AlterColumnOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterColumnOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterColumnOperation) ProtoMessage() {}

func (x *AlterColumnOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterColumnOperation.ProtoReflect.Descriptor instead.
func (*AlterColumnOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{6}
}

func (x *AlterColumnOperation) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *AlterColumnOperation) GetColumn() *v1.Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// RenameColumnOperation renames a column without changing its definition.
type RenameColumnOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldName string `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameColumnOperation) Reset() {
	*x = RenameColumnOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameColumnOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameColumnOperation) ProtoMessage() {}

func (x *RenameColumnOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameColumnOperation.ProtoReflect.Descriptor instead.
func (*RenameColumnOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{7}
}

func (x *RenameColumnOperation) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameColumnOperation) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// RenameTableOperation renames the table.
type RenameTableOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewName string `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameTableOperation) Reset() {
	*x = RenameTableOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameTableOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameTableOperation) ProtoMessage() {}

func (x *RenameTableOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameTableOperation.ProtoReflect.Descriptor instead.
func (*RenameTableOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{8}
}

func (x *RenameTableOperation) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// AlterSyncTypeOperation changes how records are synced into the table.
type AlterSyncTypeOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncType v1.TableSyncType `protobuf:"varint,1,opt,name=sync_type,json=syncType,proto3,enum=types.v1.TableSyncType" json:"sync_type,omitempty"`
}

func (x *AlterSyncTypeOperation) Reset() {
	*x = AlterSyncTypeOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterSyncTypeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterSyncTypeOperation) ProtoMessage() {}

func (x *AlterSyncTypeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterSyncTypeOperation.ProtoReflect.Descriptor instead.
func (*AlterSyncTypeOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{9}
}

func (x *AlterSyncTypeOperation) GetSyncType() v1.TableSyncType {
	if x != nil {
		return x.SyncType
	}
	return v1.TableSyncType(0)
}

// AlterTableOperation is a single DDL change applied to a table.
// Multiple operations may be batched in a single AlterTableInput.
type AlterTableOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*AlterTableOperation_AddColumn
	//	*AlterTableOperation_DropColumn
	//	*AlterTableOperation_AlterColumn
	//	*AlterTableOperation_RenameColumn
	//	*AlterTableOperation_RenameTable
	//	*AlterTableOperation_AlterSyncType
	Operation isAlterTableOperation_Operation `protobuf_oneof:"operation"`
}

func (x *AlterTableOperation) Reset() {
	*x = AlterTableOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterTableOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterTableOperation) ProtoMessage() {}

func (x *AlterTableOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterTableOperation.ProtoReflect.Descriptor instead.
func (*AlterTableOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{10}
}

func (m *AlterTableOperation) GetOperation() isAlterTableOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *AlterTableOperation) GetAddColumn() *AddColumnOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_AddColumn); ok {
		return x.AddColumn
	}
	return nil
}

func (x *AlterTableOperation) GetDropColumn() *DropColumnOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_DropColumn); ok {
		return x.DropColumn
	}
	return nil
}

func (x *AlterTableOperation) GetAlterColumn() *AlterColumnOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_AlterColumn); ok {
		return x.AlterColumn
	}
	return nil
}

func (x *AlterTableOperation) GetRenameColumn() *RenameColumnOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_RenameColumn); ok {
		return x.RenameColumn
	}
	return nil
}

func (x *AlterTableOperation) GetRenameTable() *RenameTableOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_RenameTable); ok {
		return x.RenameTable
	}
	return nil
}

func (x *AlterTableOperation) GetAlterSyncType() *AlterSyncTypeOperation {
	if x, ok := x.GetOperation().(*AlterTableOperation_AlterSyncType); ok {
		return x.AlterSyncType
	}
	return nil
}

type isAlterTableOperation_Operation interface {
	isAlterTableOperation_Operation()
}

type AlterTableOperation_AddColumn struct {
	AddColumn *AddColumnOperation `protobuf:"bytes,1,opt,name=add_column,json=addColumn,proto3,oneof"`
}

type AlterTableOperation_DropColumn struct {
	DropColumn *DropColumnOperation `protobuf:"bytes,2,opt,name=drop_column,json=dropColumn,proto3,oneof"`
}

type AlterTableOperation_AlterColumn struct {
	AlterColumn *AlterColumnOperation `protobuf:"bytes,3,opt,name=alter_column,json=alterColumn,proto3,oneof"`
}

type AlterTableOperation_RenameColumn struct {
	RenameColumn *RenameColumnOperation `protobuf:"bytes,4,opt,name=rename_column,json=renameColumn,proto3,oneof"`
}

type AlterTableOperation_RenameTable struct {
	RenameTable *RenameTableOperation `protobuf:"bytes,5,opt,name=rename_table,json=renameTable,proto3,oneof"`
}

type AlterTableOperation_AlterSyncType struct {
	AlterSyncType *AlterSyncTypeOperation `protobuf:"bytes,6,opt,name=alter_sync_type,json=alterSyncType,proto3,oneof"`
}

func (*AlterTableOperation_AddColumn) isAlterTableOperation_Operation() {}

func (*AlterTableOperation_DropColumn) isAlterTableOperation_Operation() {}

func (*AlterTableOperation_AlterColumn) isAlterTableOperation_Operation() {}

func (*AlterTableOperation_RenameColumn) isAlterTableOperation_Operation() {}

func (*AlterTableOperation_RenameTable) isAlterTableOperation_Operation() {}

func (*AlterTableOperation_AlterSyncType) isAlterTableOperation_Operation() {}

type AlterTableInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName  string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Operations []*AlterTableOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *AlterTableInput) Reset() {
	*x = AlterTableInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterTableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterTableInput) ProtoMessage() {}

func (x *AlterTableInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterTableInput.ProtoReflect.Descriptor instead.
func (*AlterTableInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{11}
}

func (x *AlterTableInput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *AlterTableInput) GetOperations() []*AlterTableOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

// AlterTableOutput returns the updated table definition after all operations
// have been applied.
type AlterTableOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table *v1.Table `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *AlterTableOutput) Reset() {
	*x = AlterTableOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterTableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterTableOutput) ProtoMessage() {}

func (x *AlterTableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterTableOutput.ProtoReflect.Descriptor instead.
func (*AlterTableOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{12}
}

func (x *AlterTableOutput) GetTable() *v1.Table {
	if x != nil {
		return x.Table
	}
	return nil
}

type TruncateTableInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *TruncateTableInput) Reset() {
	*x = TruncateTableInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruncateTableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateTableInput) ProtoMessage() {}

func (x *TruncateTableInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateTableInput.ProtoReflect.Descriptor instead.
func (*TruncateTableInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{13}
}

func (x *TruncateTableInput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type TruncateTableOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *TruncateTableOutput) Reset() {
	*x = TruncateTableOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruncateTableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateTableOutput) ProtoMessage() {}

func (x *TruncateTableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateTableOutput.ProtoReflect.Descriptor instead.
func (*TruncateTableOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{14}
}

func (x *TruncateTableOutput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type GetTableInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *GetTableInput) Reset() {
	*x = GetTableInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableInput) ProtoMessage() {}

func (x *GetTableInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableInput.ProtoReflect.Descriptor instead.
func (*GetTableInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{15}
}

func (x *GetTableInput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type GetTableOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table *v1.Table      `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Stats *v1.TableStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetTableOutput) Reset() {
	*x = GetTableOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableOutput) ProtoMessage() {}

func (x *GetTableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableOutput.ProtoReflect.Descriptor instead.
func (*GetTableOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{16}
}

func (x *GetTableOutput) GetTable() *v1.Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *GetTableOutput) GetStats() *v1.TableStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListTablesInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTablesInput) Reset() {
	*x = ListTablesInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTablesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesInput) ProtoMessage() {}

func (x *ListTablesInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesInput.ProtoReflect.Descriptor instead.
func (*ListTablesInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{17}
}

type ListTablesOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table *v1.Table      `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Stats *v1.TableStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *ListTablesOutput) Reset() {
	*x = ListTablesOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTablesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesOutput) ProtoMessage() {}

func (x *ListTablesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesOutput.ProtoReflect.Descriptor instead.
func (*ListTablesOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{18}
}

func (x *ListTablesOutput) GetTable() *v1.Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *ListTablesOutput) GetStats() *v1.TableStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CreateIndexInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *v1.Index `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *CreateIndexInput) Reset() {
	*x = CreateIndexInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndexInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexInput) ProtoMessage() {}

func (x *CreateIndexInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexInput.ProtoReflect.Descriptor instead.
func (*CreateIndexInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{19}
}

func (x *CreateIndexInput) GetIndex() *v1.Index {
	if x != nil {
		return x.Index
	}
	return nil
}

type CreateIndexOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
}

func (x *CreateIndexOutput) Reset() {
	*x = CreateIndexOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndexOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexOutput) ProtoMessage() {}

func (x *CreateIndexOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexOutput.ProtoReflect.Descriptor instead.
func (*CreateIndexOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{20}
}

func (x *CreateIndexOutput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DropIndexInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
}

func (x *DropIndexInput) Reset() {
	*x = DropIndexInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropIndexInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexInput) ProtoMessage() {}

func (x *DropIndexInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexInput.ProtoReflect.Descriptor instead.
func (*DropIndexInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{21}
}

func (x *DropIndexInput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DropIndexOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
}

func (x *DropIndexOutput) Reset() {
	*x = DropIndexOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropIndexOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexOutput) ProtoMessage() {}

func (x *DropIndexOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexOutput.ProtoReflect.Descriptor instead.
func (*DropIndexOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{22}
}

func (x *DropIndexOutput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

// RenameIndexOperation renames an index.
type RenameIndexOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewName string `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameIndexOperation) Reset() {
	*x = RenameIndexOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameIndexOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameIndexOperation) ProtoMessage() {}

func (x *RenameIndexOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameIndexOperation.ProtoReflect.Descriptor instead.
func (*RenameIndexOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{23}
}

func (x *RenameIndexOperation) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// AlterIndexOperation is a single change applied to an index.
// Currently only rename is supported in-place; other structural changes
// require DropIndex + CreateIndex.
type AlterIndexOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*AlterIndexOperation_Rename
	Operation isAlterIndexOperation_Operation `protobuf_oneof:"operation"`
}

func (x *AlterIndexOperation) Reset() {
	*x = AlterIndexOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterIndexOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterIndexOperation) ProtoMessage() {}

func (x *AlterIndexOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterIndexOperation.ProtoReflect.Descriptor instead.
func (*AlterIndexOperation) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{24}
}

func (m *AlterIndexOperation) GetOperation() isAlterIndexOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *AlterIndexOperation) GetRename() *RenameIndexOperation {
	if x, ok := x.GetOperation().(*AlterIndexOperation_Rename); ok {
		return x.Rename
	}
	return nil
}

type isAlterIndexOperation_Operation interface {
	isAlterIndexOperation_Operation()
}

type AlterIndexOperation_Rename struct {
	Rename *RenameIndexOperation `protobuf:"bytes,1,opt,name=rename,proto3,oneof"`
}

func (*AlterIndexOperation_Rename) isAlterIndexOperation_Operation() {}

type AlterIndexInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string               `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Operation *AlterIndexOperation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *AlterIndexInput) Reset() {
	*x = AlterIndexInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterIndexInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterIndexInput) ProtoMessage() {}

func (x *AlterIndexInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterIndexInput.ProtoReflect.Descriptor instead.
func (*AlterIndexInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{25}
}

func (x *AlterIndexInput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *AlterIndexInput) GetOperation() *AlterIndexOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// AlterIndexOutput returns the updated index definition after the operation
// has been applied.
type AlterIndexOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *v1.Index `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *AlterIndexOutput) Reset() {
	*x = AlterIndexOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterIndexOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterIndexOutput) ProtoMessage() {}

func (x *AlterIndexOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterIndexOutput.ProtoReflect.Descriptor instead.
func (*AlterIndexOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{26}
}

func (x *AlterIndexOutput) GetIndex() *v1.Index {
	if x != nil {
		return x.Index
	}
	return nil
}

type GetIndexInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexName string `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
}

func (x *GetIndexInput) Reset() {
	*x = GetIndexInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndexInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexInput) ProtoMessage() {}

func (x *GetIndexInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexInput.ProtoReflect.Descriptor instead.
func (*GetIndexInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{27}
}

func (x *GetIndexInput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type GetIndexOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *v1.Index `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GetIndexOutput) Reset() {
	*x = GetIndexOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndexOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexOutput) ProtoMessage() {}

func (x *GetIndexOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexOutput.ProtoReflect.Descriptor instead.
func (*GetIndexOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{28}
}

func (x *GetIndexOutput) GetIndex() *v1.Index {
	if x != nil {
		return x.Index
	}
	return nil
}

// ListIndexesInput optionally filters results to a specific table.
type ListIndexesInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// table_name, when set, restricts the response to indexes on that table.
	TableName *string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3,oneof" json:"table_name,omitempty"`
}

func (x *ListIndexesInput) Reset() {
	*x = ListIndexesInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesInput) ProtoMessage() {}

func (x *ListIndexesInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesInput.ProtoReflect.Descriptor instead.
func (*ListIndexesInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{29}
}

func (x *ListIndexesInput) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

type ListIndexesOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *v1.Index `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ListIndexesOutput) Reset() {
	*x = ListIndexesOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesOutput) ProtoMessage() {}

func (x *ListIndexesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesOutput.ProtoReflect.Descriptor instead.
func (*ListIndexesOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{30}
}

func (x *ListIndexesOutput) GetIndex() *v1.Index {
	if x != nil {
		return x.Index
	}
	return nil
}

type UpsertRecordsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*v1.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *UpsertRecordsInput) Reset() {
	*x = UpsertRecordsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertRecordsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRecordsInput) ProtoMessage() {}

func (x *UpsertRecordsInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRecordsInput.ProtoReflect.Descriptor instead.
func (*UpsertRecordsInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{31}
}

func (x *UpsertRecordsInput) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpsertRecordsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// records_affected is the number of rows inserted or updated.
	RecordsAffected uint64 `protobuf:"varint,1,opt,name=records_affected,json=recordsAffected,proto3" json:"records_affected,omitempty"`
}

func (x *UpsertRecordsOutput) Reset() {
	*x = UpsertRecordsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertRecordsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRecordsOutput) ProtoMessage() {}

func (x *UpsertRecordsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRecordsOutput.ProtoReflect.Descriptor instead.
func (*UpsertRecordsOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{32}
}

func (x *UpsertRecordsOutput) GetRecordsAffected() uint64 {
	if x != nil {
		return x.RecordsAffected
	}
	return 0
}

type DeleteRecordsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// records identifies the rows to delete. Only primary key column values are
	// used; non-key columns in each Record are ignored.
	Records []*v1.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *DeleteRecordsInput) Reset() {
	*x = DeleteRecordsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsInput) ProtoMessage() {}

func (x *DeleteRecordsInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsInput.ProtoReflect.Descriptor instead.
func (*DeleteRecordsInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteRecordsInput) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type DeleteRecordsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// records_deleted is the number of rows removed.
	RecordsDeleted uint64 `protobuf:"varint,1,opt,name=records_deleted,json=recordsDeleted,proto3" json:"records_deleted,omitempty"`
}

func (x *DeleteRecordsOutput) Reset() {
	*x = DeleteRecordsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsOutput) ProtoMessage() {}

func (x *DeleteRecordsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsOutput.ProtoReflect.Descriptor instead.
func (*DeleteRecordsOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteRecordsOutput) GetRecordsDeleted() uint64 {
	if x != nil {
		return x.RecordsDeleted
	}
	return 0
}

type SyncDataInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoCreateTables bool             `protobuf:"varint,1,opt,name=auto_create_tables,json=autoCreateTables,proto3" json:"auto_create_tables,omitempty"`
	SyncType         v1.TableSyncType `protobuf:"varint,2,opt,name=sync_type,json=syncType,proto3,enum=types.v1.TableSyncType" json:"sync_type,omitempty"`
	Records          []*v1.Record     `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *SyncDataInput) Reset() {
	*x = SyncDataInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataInput) ProtoMessage() {}

func (x *SyncDataInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataInput.ProtoReflect.Descriptor instead.
func (*SyncDataInput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{35}
}

func (x *SyncDataInput) GetAutoCreateTables() bool {
	if x != nil {
		return x.AutoCreateTables
	}
	return false
}

func (x *SyncDataInput) GetSyncType() v1.TableSyncType {
	if x != nil {
		return x.SyncType
	}
	return v1.TableSyncType(0)
}

func (x *SyncDataInput) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// SyncDataOutput acknowledges a processed batch from the client stream.
type SyncDataOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// table_name identifies the table this acknowledgment refers to.
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// records_processed is the cumulative count of records committed for this
	// table within the current stream.
	RecordsProcessed uint64 `protobuf:"varint,2,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
}

func (x *SyncDataOutput) Reset() {
	*x = SyncDataOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_push_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataOutput) ProtoMessage() {}

func (x *SyncDataOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_push_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataOutput.ProtoReflect.Descriptor instead.
func (*SyncDataOutput) Descriptor() ([]byte, []int) {
	return file_api_v1_push_proto_rawDescGZIP(), []int{36}
}

func (x *SyncDataOutput) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SyncDataOutput) GetRecordsProcessed() uint64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

var File_api_v1_push_proto protoreflect.FileDescriptor

var file_api_v1_push_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x39, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x32, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03,
	0x18, 0x3f, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a,
	0x0f, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x3e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22,
	0x41, 0x0a, 0x13, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06,
	0x72, 0x04, 0x10, 0x02, 0x18, 0x3f, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x6c, 0x0a, 0x14, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x0b, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x02, 0x18, 0x3f, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x22, 0x63, 0x0a, 0x15, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x6f, 0x6c, 0x64,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06,
	0x72, 0x04, 0x10, 0x02, 0x18, 0x3f, 0x52, 0x07, 0x6f, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x24, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x02, 0x18, 0x3f, 0x52, 0x07, 0x6e, 0x65,
	0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x14, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x58, 0x0a, 0x16, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a,
	0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x42, 0x08, 0xba, 0x48, 0x05, 0x82, 0x01,
	0x02, 0x10, 0x01, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0xb5, 0x03,
	0x0a, 0x13, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x41, 0x0a, 0x0c, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x44, 0x0a, 0x0d, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x41, 0x0a, 0x0c, 0x72,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0b, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x48,
	0x0a, 0x0f, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x6c, 0x74, 0x65, 0x72,
	0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba,
	0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0xba, 0x48, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0a,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x39, 0x0a, 0x10, 0x41, 0x6c,
	0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25,
	0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0a, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x13, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0a,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x09, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x65,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x32, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72,
	0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x30, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x14, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x6e, 0x65,
	0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48,
	0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x5a, 0x0a, 0x13, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x0f,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x28, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52, 0x09,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x10, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x28, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x52,
	0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x50, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06,
	0x72, 0x04, 0x10, 0x03, 0x18, 0x3f, 0x48, 0x00, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x4a, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x08, 0xba, 0x48, 0x05, 0x92,
	0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x40, 0x0a,
	0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f,
	0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22,
	0x4a, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x08, 0xba, 0x48, 0x05, 0x92, 0x01, 0x02,
	0x08, 0x01, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x3e, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x0d,
	0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2c, 0x0a,
	0x12, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x61, 0x75, 0x74, 0x6f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x73,
	0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x42, 0x08, 0xba, 0x48, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x5c, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x63, 0x62, 0x65, 0x72, 0x75, 0x73, 0x2f, 0x67, 0x6f, 0x2d,
	0x70, 0x75, 0x73, 0x68, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_push_proto_rawDescOnce sync.Once
	file_api_v1_push_proto_rawDescData = file_api_v1_push_proto_rawDesc
)

func file_api_v1_push_proto_rawDescGZIP() []byte {
	file_api_v1_push_proto_rawDescOnce.Do(func() {
		file_api_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_push_proto_rawDescData)
	})
	return file_api_v1_push_proto_rawDescData
}

var file_api_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_v1_push_proto_goTypes = []interface{}{
	(*CreateTableInput)(nil),       // 0: api.v1.CreateTableInput
	(*CreateTableOutput)(nil),      // 1: api.v1.CreateTableOutput
	(*DropTableInput)(nil),         // 2: api.v1.DropTableInput
	(*DropTableOutput)(nil),        // 3: api.v1.DropTableOutput
	(*AddColumnOperation)(nil),     // 4: api.v1.AddColumnOperation
	(*DropColumnOperation)(nil),    // 5: api.v1.DropColumnOperation
	(*AlterColumnOperation)(nil),   // 6: api.v1.AlterColumnOperation
	(*RenameColumnOperation)(nil),  // 7: api.v1.RenameColumnOperation
	(*RenameTableOperation)(nil),   // 8: api.v1.RenameTableOperation
	(*AlterSyncTypeOperation)(nil), // 9: api.v1.AlterSyncTypeOperation
	(*AlterTableOperation)(nil),    // 10: api.v1.AlterTableOperation
	(*AlterTableInput)(nil),        // 11: api.v1.AlterTableInput
	(*AlterTableOutput)(nil),       // 12: api.v1.AlterTableOutput
	(*TruncateTableInput)(nil),     // 13: api.v1.TruncateTableInput
	(*TruncateTableOutput)(nil),    // 14: api.v1.TruncateTableOutput
	(*GetTableInput)(nil),          // 15: api.v1.GetTableInput
	(*GetTableOutput)(nil),         // 16: api.v1.GetTableOutput
	(*ListTablesInput)(nil),        // 17: api.v1.ListTablesInput
	(*ListTablesOutput)(nil),       // 18: api.v1.ListTablesOutput
	(*CreateIndexInput)(nil),       // 19: api.v1.CreateIndexInput
	(*CreateIndexOutput)(nil),      // 20: api.v1.CreateIndexOutput
	(*DropIndexInput)(nil),         // 21: api.v1.DropIndexInput
	(*DropIndexOutput)(nil),        // 22: api.v1.DropIndexOutput
	(*RenameIndexOperation)(nil),   // 23: api.v1.RenameIndexOperation
	(*AlterIndexOperation)(nil),    // 24: api.v1.AlterIndexOperation
	(*AlterIndexInput)(nil),        // 25: api.v1.AlterIndexInput
	(*AlterIndexOutput)(nil),       // 26: api.v1.AlterIndexOutput
	(*GetIndexInput)(nil),          // 27: api.v1.GetIndexInput
	(*GetIndexOutput)(nil),         // 28: api.v1.GetIndexOutput
	(*ListIndexesInput)(nil),       // 29: api.v1.ListIndexesInput
	(*ListIndexesOutput)(nil),      // 30: api.v1.ListIndexesOutput
	(*UpsertRecordsInput)(nil),     // 31: api.v1.UpsertRecordsInput
	(*UpsertRecordsOutput)(nil),    // 32: api.v1.UpsertRecordsOutput
	(*DeleteRecordsInput)(nil),     // 33: api.v1.DeleteRecordsInput
	(*DeleteRecordsOutput)(nil),    // 34: api.v1.DeleteRecordsOutput
	(*SyncDataInput)(nil),          // 35: api.v1.SyncDataInput
	(*SyncDataOutput)(nil),         // 36: api.v1.SyncDataOutput
	(*v1.Table)(nil),               // 37: types.v1.Table
	(*v1.Column)(nil),              // 38: types.v1.Column
	(v1.TableSyncType)(0),          // 39: types.v1.TableSyncType
	(*v1.TableStats)(nil),          // 40: types.v1.TableStats
	(*v1.Index)(nil),               // 41: types.v1.Index
	(*v1.Record)(nil),              // 42: types.v1.Record
}
var file_api_v1_push_proto_depIdxs = []int32{
	37, // 0: api.v1.CreateTableInput.table:type_name -> types.v1.Table
	38, // 1: api.v1.AddColumnOperation.column:type_name -> types.v1.Column
	38, // 2: api.v1.AlterColumnOperation.column:type_name -> types.v1.Column
	39, // 3: api.v1.AlterSyncTypeOperation.sync_type:type_name -> types.v1.TableSyncType
	4,  // 4: api.v1.AlterTableOperation.add_column:type_name -> api.v1.AddColumnOperation
	5,  // 5: api.v1.AlterTableOperation.drop_column:type_name -> api.v1.DropColumnOperation
	6,  // 6: api.v1.AlterTableOperation.alter_column:type_name -> api.v1.AlterColumnOperation
	7,  // 7: api.v1.AlterTableOperation.rename_column:type_name -> api.v1.RenameColumnOperation
	8,  // 8: api.v1.AlterTableOperation.rename_table:type_name -> api.v1.RenameTableOperation
	9,  // 9: api.v1.AlterTableOperation.alter_sync_type:type_name -> api.v1.AlterSyncTypeOperation
	10, // 10: api.v1.AlterTableInput.operations:type_name -> api.v1.AlterTableOperation
	37, // 11: api.v1.AlterTableOutput.table:type_name -> types.v1.Table
	37, // 12: api.v1.GetTableOutput.table:type_name -> types.v1.Table
	40, // 13: api.v1.GetTableOutput.stats:type_name -> types.v1.TableStats
	37, // 14: api.v1.ListTablesOutput.table:type_name -> types.v1.Table
	40, // 15: api.v1.ListTablesOutput.stats:type_name -> types.v1.TableStats
	41, // 16: api.v1.CreateIndexInput.index:type_name -> types.v1.Index
	23, // 17: api.v1.AlterIndexOperation.rename:type_name -> api.v1.RenameIndexOperation
	24, // 18: api.v1.AlterIndexInput.operation:type_name -> api.v1.AlterIndexOperation
	41, // 19: api.v1.AlterIndexOutput.index:type_name -> types.v1.Index
	41, // 20: api.v1.GetIndexOutput.index:type_name -> types.v1.Index
	41, // 21: api.v1.ListIndexesOutput.index:type_name -> types.v1.Index
	42, // 22: api.v1.UpsertRecordsInput.records:type_name -> types.v1.Record
	42, // 23: api.v1.DeleteRecordsInput.records:type_name -> types.v1.Record
	39, // 24: api.v1.SyncDataInput.sync_type:type_name -> types.v1.TableSyncType
	42, // 25: api.v1.SyncDataInput.records:type_name -> types.v1.Record
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_api_v1_push_proto_init() }
func file_api_v1_push_proto_init() {
	if File_api_v1_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTableInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTableOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddColumnOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropColumnOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterColumnOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameColumnOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameTableOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterSyncTypeOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterTableOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterTableInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterTableOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TruncateTableInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TruncateTableOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTablesInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTablesOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndexInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIndexOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropIndexInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropIndexOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameIndexOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterIndexOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterIndexInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterIndexOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndexInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndexOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertRecordsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertRecordsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_push_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_push_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*AlterTableOperation_AddColumn)(nil),
		(*AlterTableOperation_DropColumn)(nil),
		(*AlterTableOperation_AlterColumn)(nil),
		(*AlterTableOperation_RenameColumn)(nil),
		(*AlterTableOperation_RenameTable)(nil),
		(*AlterTableOperation_AlterSyncType)(nil),
	}
	file_api_v1_push_proto_msgTypes[24].OneofWrappers = []interface{}{
		(*AlterIndexOperation_Rename)(nil),
	}
	file_api_v1_push_proto_msgTypes[29].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_push_proto_goTypes,
		DependencyIndexes: file_api_v1_push_proto_depIdxs,
		MessageInfos:      file_api_v1_push_proto_msgTypes,
	}.Build()
	File_api_v1_push_proto = out.File
	file_api_v1_push_proto_rawDesc = nil
	file_api_v1_push_proto_goTypes = nil
	file_api_v1_push_proto_depIdxs = nil
}
